server:
  port: 8085

spring:
  profiles: default
  application:
    name: ocbpoint-service
  datasource:
    url: jdbc:mysql://localhost:3306/muffin
    username: root
    password:
    initialization-mode: always 
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9091/eureka

logging:
  level: 
    org.hibernate.type: trace
    
---
spring:
  profiles: docker
  application:
    name: ocbpoint-service
  datasource:
    url: jdbc:mysql://mysql:3306/muffin
    username: root
    password:
    initialization-mode: always 
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka1:9092
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:9091/eureka

logging:
  level: 
    org.hibernate.type: trace

---
spring:
  profiles: k8s
  application:
    name: ocbpoint-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_INFO}
    username: root
    password:
    initialization-mode: always 
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_SERVER_INFO}
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:9091/eureka

logging:
  level: 
    org.hibernate.type: trace
