apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: muffin-order
        image: icepegasus/muffin-order
        env:
        - name: MYSQL_SERVER_INFO
          value: "mysql-svc:3306/muffin"
        - name: KAFKA_SERVER_INFO
          value: "kafka-svc:9092"
      terminationGracePeriodSeconds: 0
---

apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  type: NodePort