# Maven build stage
FROM maven:3.6.3-openjdk-8 as maven
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY . .	
RUN mvn clean package -Dmaven.test.skip=true

# Package stage
FROM adoptopenjdk/openjdk8:alpine-jre
COPY --from=maven target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.profiles.active=docker","-jar","/app.jar"]