version: "3"

services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: muffin
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - default_net
    volumes:
      - sqldb:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis-container:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks: 
      - default_net
    volumes:
      - redis-data:/data

networks:
  default_net:
    driver: "bridge"

volumes:
  sqldb:
  redis-data:
