spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:9090
      name: ${spring.application.name},muffin
      failFast: true
      retry:
        maxAttempts: 20
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: memberService
          uri: http://localhost:8081
          predicates:
            - Path=/members/**
        - id: stationService
          uri: http://localhost:8082
          predicates:
            - Path=/stations/**
        - id: orderService
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
        - id: ocbPointService
          uri: http://localhost:8085
          predicates:
            - Path=/ocbPoints/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka

server:
  port: 8080

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-service:9090
      name: ${spring.application.name},eshop
      failFast: true
      retry:
        maxAttempts: 20
    gateway:
      routes:
        - id: userService
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: productService
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
        - id: orderService
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**
        - id: cartService
          uri: http://cart-service:8084
          predicates:
            - Path=/cart/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka