server:
  port: 8083

spring:
  profiles: default
  application:
    name: order-service
    
  datasource:
    url: jdbc:mysql://localhost:3307/muffin
    username: root
    password:
    initialization-mode: always 
      
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    

    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka

logging:
  level: 
    org.hibernate.type: trace