server:
  port: 8081

spring:
  profiles: default
  application:
    name: member-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
          
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
   
  datasource:
    url: jdbc:h2:mem:account
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9091/eureka

logging:
  level: 
    org.hibernate.type: trace
    
---
spring:
  profiles: docker
  application:
    name: member-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka1:9092
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
          
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
   
  datasource:
    url: jdbc:h2:mem:account
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:9091/eureka

logging:
  level: 
    org.hibernate.type: trace
    
    
---
spring:
  profiles: k8s
  application:
    name: member-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_SERVER_INFO}
        streams:
          binder:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orders${random.value}
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
          
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
   
  datasource:
    url: jdbc:h2:mem:account
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:9091/eureka

logging:
  level: 
    org.hibernate.type: trace
